# Generated by Django 3.2.6 on 2021-08-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pump_name', models.CharField(max_length=100)),
                ('pump_address', models.TextField()),
                ('price', models.IntegerField()),
                ('pump_distance', models.IntegerField()),
                ('pump_image', models.CharField(max_length=500)),
                ('emenities', models.ManyToManyField(to='home.Emenities')),
            ],
        ),
    ]
