# Generated by Django 3.2.6 on 2021-08-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gas',
            old_name='price',
            new_name='available_amount',
        ),
        migrations.RemoveField(
            model_name='gas',
            name='pump_distance',
        ),
        migrations.AlterField(
            model_name='gas',
            name='pump_image',
            field=models.FileField(upload_to='post_image'),
        ),
    ]
