# Generated by Django 3.2.6 on 2021-08-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210822_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gas',
            name='pump_image',
            field=models.CharField(max_length=500),
        ),
    ]
